---
title: "Professional Learning Evaluation Plan"
output: 
  distill::distill_article:
    css: "css/strapless.css"
---

<h4 style="color: #FF7B43;font-size:x-large;">Background</h3>
<p>Teaching Lab&rsquo;s mission is to fundamentally shift the paradigm of teacher professional learning (PL) to achieve educational equity. In our fourth full-year of implementation of professional learning with school partners, Teaching Lab seeks to answer the following questions about the impact of our work:&nbsp;</p>
<ol>
<li>To what extent do teachers experience and sustain a change in equitable mindsets, content and pedagogical content knowledge, and equitable teaching practices after participating in Teaching Lab PL?</li>
<li>To what extent do the learning experiences and academic outcomes of students of teachers who participate in Teaching Lab PL experience improve?</li>
</ol>
<p>Our theory of evaluation for our professional learning model is adapted from the Guskey (2009) framework: If teachers find their professional learning experience valuable (<strong>participant perceptions</strong>), if they increase content and pedagogical content knowledge (<strong>participant knowledge</strong>), if they have an equitable mindset and high expectations for all students (<strong>participant mindsets</strong>), if they have the conducive environment for professional learning (<strong>enabling conditions</strong>), and if they enact evidence-based instructional practices in the classroom (<strong>participant practices</strong>), then their students will have improved learning outcomes (<strong>student learning experiences</strong>).</p>
<p>Teaching Lab has designed a rigorous evaluation plan of our professional learning, with multiple venues for collecting data about each component within our theory of evaluation. We have obtained agreements from almost every single one of our system partners to engage in data collection, and we are excited to triangulate various data points to tell the story of where Teaching Lab is changing teaching and learning, and where we can adapt our model to reach even better results.&nbsp;</p>
<p>In addition to our internal evaluation plan, Teaching Lab is engaged in external evaluation studies led by prominent education researchers, Dr. Heather Hill, Dr. John Papay, and Dr. David Blazar, as well as the The Bill &amp; Melinda Gates Foundation. These studies will&nbsp; measure changes in teacher mindsets, knowledge, and practices in addition to&nbsp; student learning experiences and outcomes, both academic and social emotional, to better understand the impact ofTeaching Lab professional learning.</p>
<h4 style="color: #FF7B43;font-size:x-large;">What We Measure</h3>
<p>The following describes how we plan to learn about each component of our theory of evaluation:&nbsp;</p>
<ol>
<li><strong>Participant perceptions</strong>:</li>
<ol>
<li>We administer an <a href="https://docs.google.com/document/d/1hcpZOk-6IODD3ApZxWhd7_6hlsA2tVuHYWDNnGVw1RQ/edit?usp=sharing" target="_blank" rel="noopener">End-of-Session Survey</a> which allows us to learn about participants&rsquo; feedback of the facilitation and the overall quality and content of the sessions. We use this information to make real-time adjustments to facilitation.</li>
<li>We also administer an <a href="https://docs.google.com/document/d/1hcpZOk-6IODD3ApZxWhd7_6hlsA2tVuHYWDNnGVw1RQ/edit" target="_blank" rel="noopener">End-of-Course Survey</a>, which allows us to learn whether participants believe the PL is high quality, relevant, and feasible, and whether they would recommend it to others (Net Promoter Score). We use this information to make any necessary changes to the course structure and/or content focus.</li>
</ol>
<li><strong>Participant knowledge</strong>:&nbsp;</li>
<ol>
<li>During the first session, participants complete a <a href="https://docs.google.com/document/d/1t43JudOR4AlIk8ALdPp1V9UgZH8mWmybrDdDp2085mQ/edit?usp=sharing" target="_blank" rel="noopener">short knowledge assessment </a>consisting of multiple-choice quiz questions about the specific content and pedagogical content knowledge addressed in the sequence of learning for a content area. We use this information to adjust facilitation as needed. During the last session, they complete the same set of multiple-choice quiz questions. We use this information to track how participant knowledge changes.</li>
</ol>
<li><strong>Participant mindsets</strong>:&nbsp;</li>
<ol>
<li>We conducted a literature review to identify key teacher mindsets and expectations which are most predictive of student learning outcomes, particularly the outcomes of students of color: recognition of race and culture, high expectations that all students can and will learn, and growth mindsets. Moreover, we have incorporated items on self-efficacy to deliver culturally responsive instruction, which is linked to high expectations and effective teaching practices. We&rsquo;ve adapted the questions on teacher mindsets to be relevant for coaches and school leaders. We continue to integrate these mindsets into our PL sequence.</li>
<li>We ask about these characteristics in our Diagnostic Educator Survey and Follow-up Educator Survey. We use this information to track how participant mindsets change throughout our partnership.&nbsp;</li>
<li>The mindset questions can be found in the <a href="https://docs.google.com/document/d/1hcldd1oL5Y0SA3kUl1cCYeZmDIDv_KCbcT7Z4Z0tfUQ/edit?usp=sharing" target="_blank" rel="noopener">Mindsets and Expectations</a> section of our Educator Survey.</li>
<li>We also triangulate these survey responses with students&rsquo; perceptions of their learning experience. Read more about our work on the student perception survey in the &ldquo;Student learning experiences&rdquo; section below.</li>
</ol>
<li><strong>Supportive structures and environment</strong>: Teaching Lab&rsquo;s grassroots model of professional learning leans on the core belief that teachers deserve to feel motivated and supported by their peers to learn and grow. In teacher-led communities, educators are more likely to buy into their own development and work collaboratively with their colleagues to improve instruction. We call this the &ldquo;heart&rdquo; of professional learning.&nbsp;</li>
<ol>
<li>In our Diagnostic Educator Survey and Follow-up Educator Survey, we ask teachers about their <strong>trust</strong> of other teachers, and the level of <strong>collaboration</strong> they have with others in their schools, which are parts of teacher social capital. We use this information to track how teacher social capital changes throughout our partnership.</li>
<li>The supportive structures and environment questions can be found in the <a href="https://docs.google.com/document/d/1hcldd1oL5Y0SA3kUl1cCYeZmDIDv_KCbcT7Z4Z0tfUQ/edit?usp=sharing" target="_blank" rel="noopener">School Environment</a> section of our Diagnostic Educator Survey and Follow-up Educator Survey.</li>
</ol>
<li><strong>Participant practices</strong>:&nbsp;</li>
<ol>
<li>Our team conducts classroom observations and takes the opportunity to capture <a href="https://achievethecore.org/category/1155/printable-versions" target="_blank" rel="noopener">standards-and-shifts-aligned instruction</a> using a subset of core actions from the Instructional Practice Guides which are most emphasized in our learning sequence (e.g., citing relevant evidence, productive struggle, student talk) throughout our partnership.&nbsp;</li>
<li>We also sign data agreements with state education agencies and districts when possible to obtain <strong>teacher evaluation data</strong> to compare the effectiveness of teachers participating in our professional learning sequences compared to other teachers.&nbsp;</li>
</ol>
<li><strong>Student learning experiences</strong>: Our ultimate goal is to increase student learning and achieve educational equity.&nbsp;</li>
<ol>
<li>We conducted a literature review to identify key dimensions of <strong>student learning experiences</strong> that are within teachers&rsquo; control and highly predictive of student learning outcomes: student-teacher relationships, self-efficacy, growth mindset, happiness and sense of belonging, being challenged and culturally responsive teaching practices. We ask about these dimensions in our <a href="https://docs.google.com/document/d/1BtrBPIWNtsEeJa4KTLiUHZba54tLnn_4NZe5DBPmHp0/edit" target="_blank" rel="noopener">twice-a-year student survey</a> based on Transcend&rsquo;s Leaps Student Voice Survey.</li>
<li>We also collect and analyze <a href="https://docs.google.com/document/d/1HXPLYYT6bMpija8BwLO707DEHUbKDHOQ7glRwpEIMUk/edit" target="_blank" rel="noopener">student tasks </a>from the same students multiple times throughout the school year to track the quality of student tasks and student performance on rigorous, grade-level tasks throughout our partnership.</li>
<li>We sign data agreements with state education agencies and districts when possible to obtain <strong>student formative and/or summative assessment data</strong> to track learning.</li>
</ol>
</ol>