---
title: "<center>Teaching Lab Website</center>"
---

<center>
Site currently under maintenance, lots more to come soon though!
</center>

```{r echo = F, warning = F, message = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(ggiraph)
library(tidyverse)

theme_set(theme_minimal())
```



<br>
<br>

<center> Hover Over Points Below to Read Teaching Lab Professional Development Reviews </center>

<br>
<br>

```{r}
plot_data <- readr::read_rds(here::here("Data/dashboard_data.rds")) %>%
  mutate(`How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?` = as.numeric(`How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?`))

guidebooks <- c("Guidebooks|GuideBooks")

not_state_level <- c("EL|IM|Guidebooks|GuideBooks")

sorted_teaching_df <- plot_data %>%
  filter(`Overall, what went well in this professional learning?` != "No Response") %>%
  # filter(`Date for the session` >= "2020-06-30") %>%
  group_by(`Date for the session`) %>%
  mutate(pro_grouping = case_when(!str_detect(`Professional Training Session`, not_state_level) == T ~ "State-Level",
                                  str_detect(`Professional Training Session`, "IM") == T ~ "Illustrative Mathematics",
                                  str_detect(`Professional Training Session`, guidebooks) == T ~ "Guidebooks",
                                  str_detect(`Professional Training Session`, "EL") == T ~ "EL")) %>%
  drop_na(`How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?`,
          pro_grouping) %>%
  group_by(pro_grouping) %>%
  # Means before and after pandemic by type of training session
  mutate(grouped_means = mean(`How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?`, na.rm = T)) %>%
  mutate(pro_grouping = forcats::fct_reorder(pro_grouping, -grouped_means)) %>%
  ungroup() %>%
  # Means of before and after pandemic
  mutate(mean_score = mean(`How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?`)) %>%
  ungroup()

# Axis colors 
axis_colors <- c("#040404", "#324D56", "#346475", "#04ABEB")

col <- colorRampPalette(rev(axis_colors))

# Make the graph aesthetics, theme, and limits
g <- ggplot(sorted_teaching_df, aes(
              x = fct_rev(pro_grouping), 
              y = `How Likely Are You To Recommend This Professional Learning To A Colleague Or Friend?`, 
              color = pro_grouping
  )) +
  scale_y_continuous(limits = c(0, 10), breaks = scales::breaks_pretty(n = 10)) +
  scale_color_manual(values = col(4)) +
  coord_flip() +
  labs(x = "", y = "Likeliness to Recommend to a Friend or Colleague", title = "Explore Teaching Lab Reviews") +
  theme(legend.position = "none",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5, family = "Calibri", size = 30, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, family = "Calibri"),
        panel.grid = element_blank(),
        axis.title.y = element_text(family = "Calibri", size = 22),
        axis.title.x = element_text(family = "Calibri", size = 22),
        axis.text.x = element_text(color = "#324D56", family = "Calibri", 
                                   margin = unit(c(0, 0, -0.2, 0), "cm"),
                                   vjust = 10,
                                   size = 15),
        axis.text.y = element_text(color= axis_colors, family = "Calibri", size = 15),
        axis.ticks.x = element_line(size = 3, color = "#324D56", linetype = 2),
        axis.ticks.length.x = unit(0.2, "cm"))


# Graph with geoms applied for baselayer test
graph <- g + 
  geom_segment(
    aes(x = fct_rev(pro_grouping), xend = fct_rev(pro_grouping),
        y = mean_score, yend = grouped_means),
    show.legend = F,
    size = 0.8
  ) +
  geom_jitter(size = 3, height = 0.15) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  geom_hline(aes(yintercept = mean_score), color = "gray70")

final_graph <- graph +
  geom_segment(
    aes(x = fct_rev(pro_grouping), xend = fct_rev(pro_grouping),
        y = mean_score, yend = grouped_means),
    show.legend = F,
    size = 0.8
  ) +
  ggiraph::geom_jitter_interactive(size = 3, aes(alpha = 0.8,
                            tooltip = paste(`District, Parish, Or Network`, 
                                            `Professional Training Session`,
                                            paste0("\"",
                                            `Overall, what went well in this professional learning?`,
                                            "\""
                                            ),
                                            sep = "\n")), 
              height = 0.15, width = 0.1) + # Height changes width here since coord_flip already happened
  # scale_alpha_manual(values = c(0.6, 0.2)) + # Manually change the alpha since they need to be set for different n
  stat_summary(fun = mean, geom = "point", size = 5) + # Add mean summary point
  geom_hline(aes(yintercept = mean_score), color = "gray70")

tooltip_css <- "font-family:'Calibri';color:white;"
html_plot <- girafe(ggobj = final_graph, fonts = list(sans = "Calibri"),
       options = list(
         opts_tooltip(offx = 15, offy = 15, use_cursor_pos = T, use_fill = T, css = tooltip_css),
         opts_sizing(rescale = T, width = 1),
         opts_hover_inv(css = "opacity:0.5;"),
         opts_toolbar(saveaspng = F)
         ),
       width_svg = 32, height_svg = 20
       ) #%>%# Real size
  # girafe_options(.,
  #                htmlwidgets::sizingPolicy(padding = "5px",
  #                                          defaultWidth = "150%", defaultHeight = "150%"))

html_plot
```

