---
title: "Reports Hub"
output: 
  distill::distill_article:
    css: "css/strapless.css"
---

# SY21-22 Mid-Year Reports

<br>

<center> Passwords for Reports are <a href="https://docs.google.com/spreadsheets/d/1eAUdWEzc0R7WzpztOvutRp2FYDtpks37LSFV8sq8ezg/edit?usp=sharing" target="_blank">here</a> which will only be viewable if you are a Teaching Lab employee. Different tabs within the spreadsheet contain the passwords for each year. </center>

<br>

```{r echo = F, layout = "l-page"}
library(bs4cards)
report_galleries <- tibble::tibble(
  location = c("All Partners",
  "Brownington Central School, VT",
  "Building 21 - Allentown, PA",
  "Building 21 - Philadelphia, PA",
  "Calcasieu Parish, LA",
  "Cleveland Metropolitan School District, OH",
  "Connecticut Partnership (with UnboundEd)",
  "Delaware Department of Education, DE",
  "DeSoto Parish, LA",
  "District 11",
  "District 11 ELA",
  "District 11 Math",
  "Freire Charter Schools, PA/DE",
  "Horizon Charter Schools, CA",
  "Kankakee School District, IL",
  "Lafayette Parish, LA",
  "Louisiana Department of Education, LA",
  "Louisville School District - Jacob Elementary, KY",
  "Massachusetts Dept of Elementary & Secondary Education",
  "Methuen Public Schools, MA",
  "Mississippi Department of Education, MS",
  "North Bronx School of Empowerment, NY",
  "NYC District 6 - MS311, NY",
  "NYC District 9",
  "NYC District 12 - EMST-IS 190, N",
  "NYC District 12 - MS 286, NY",
  "Open Enrollment, National",
  "Orleans Central Supervisory Union, VT",
  "Pointe Coupee Parish, LA",
  "Rochester City School District",
  "San Diego 6-8",
  "San Diego K-5",
  "San Diego Unified School District, CA",
  "Washington Parish, LA",
  "West Contra Costa USD - Murphy Elementary, CA",
  "West Contra Costa USD, CA",
  "Wisconsin Department of Public Instruction"),
  long_name = c("All Partners Report",
  "Brownington Central School, VT Report",
  "Building 21 - Allentown, PA Report",
  "Building 21 - Philadelphia, PA Report",
  "Calcasieu Parish, LA Report",
  "Cleveland Metropolitan School District, OH Report",
  "Connecticut Partnership (with UnboundEd) Report",
  "Delaware Department of Education, DE Report",
  "DeSoto Parish, LA Report",
  "District 11 Report",
  "District 11 ELA Report",
  "District 11 Math Report",
  "Freire Charter Schools, PA/DE Report",
  "Horizon Charter Schools, CA Report",
  "Kankakee School District, IL Report",
  "Lafayette Parish, LA Report",
  "Louisiana Department of Education, LA Report",
  "Louisville School District - Jacob Elementary, KY Report",
  "Massachusetts Dept of Elementary & Secondary Education Report",
  "Methuen Public Schools, MA Report",
  "Mississippi Department of Education, MS Report",
  "North Bronx School of Empowerment, NY Report",
  "NYC District 6 - MS311, NY Report",
  "NYC District 9 Report",
  "NYC District 12 - EMST-IS 190, N Report",
  "NYC District 12 - MS 286, NY Report",
  "Open Enrollment, National Report",
  "Orleans Central Supervisory Union, VT Report",
  "Pointe Coupee Parish, LA Report",
  "Rochester City School District Report",
  "San Diego 6-8 Report",
  "San Diego K-5 Report",
  "San Diego Unified School District, CA Report",
  "Washington Parish, LA Report",
  "West Contra Costa USD - Murphy Elementary, CA Report",
  "West Contra Costa USD, CA Report",
  "Wisconsin Department of Public Instruction Report"),
  image_url = c(
    here::here("Images/Reports/Midyear/2021-2022-tl-report_All Partners.png"),
    here::here("Images/Reports/Midyear/2021-2022-tl-report_Brownington Central School, VT.png"),
    here::here("Images/Reports/Midyear/2021-2022-tl-report_Building 21 - Allentown, PA.png"),
    here::here("Images/Reports/Midyear/2021-2022-tl-report_Building 21 - Philadelphia, PA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Calcasieu Parish, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Cleveland Metropolitan School District, OH.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Connecticut Partnership (with UnboundEd).png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Delaware Department of Education, DE.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_DeSoto Parish, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_District 11.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_District 11 ELA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_District 11 Math.png"),
  here::here("Images/Reports/Midyear/DE.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Horizon Charter Schools, CA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Kankakee School District, IL.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Lafayette Parish, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Louisiana Department of Education, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Louisville School District - Jacob Elementary, KY.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Massachusetts Dept of Elementary and Secondary Education.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Methuen Public Schools, MA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Mississippi Department of Education, MS.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_North Bronx School of Empowerment, NY.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_NYC District 6 - MS311, NY.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_NYC District 9.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_NYC District 12 - EMST-IS 190, N.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_NYC District 12 - MS 286, NY.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Open Enrollment, National.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Orleans Central Supervisory Union, VT.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Pointe Coupee Parish, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Rochester City School District.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_San Diego 6-8.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_San Diego K-5.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_San Diego Unified School District, CA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Washington Parish, LA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_West Contra Costa USD - Murphy Elementary, CA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_West Contra Costa USD, CA.png"),
  here::here("Images/Reports/Midyear/2021-2022-tl-report_Wisconsin Department of Public Instruction.png")),
  link = c("2022Reports/Encrypted/2021-2022-tl-report_All Partners-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Brownington Central School, VT-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Building 21 - Allentown, PA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Building 21 - Philadelphia, PA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Calcasieu Parish, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Cleveland Metropolitan School District, OH-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Connecticut Partnership (with UnboundEd)-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Delaware Department of Education, DE-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_DeSoto Parish, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_District 11-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_District 11 ELA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_District 11 Math-protected.html",
  "2022Reports/Encrypted/DE-protected.html", # Freire for some reason
  "2022Reports/Encrypted/2021-2022-tl-report_Horizon Charter Schools, CA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Kankakee School District, IL-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Lafayette Parish, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Louisiana Department of Education, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Louisville School District - Jacob Elementary, KY-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Massachusetts Dept of Elementary & Secondary Education-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Methuen Public Schools, MA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Mississippi Department of Education, MS-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_North Bronx School of Empowerment, NY-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_NYC District 6 - MS311, NY-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_NYC District 9-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_NYC District 12 - EMST-IS 190, N-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_NYC District 12 - MS 286, NY-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Open Enrollment, National-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Orleans Central Supervisory Union, VT-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Pointe Coupee Parish, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Rochester City School District-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_San Diego 6-8-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_San Diego K-5-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_San Diego Unified School District, CA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Washington Parish, LA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_West Contra Costa USD - Murphy Elementary, CA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_West Contra Costa USD, CA-protected.html",
  "2022Reports/Encrypted/2021-2022-tl-report_Wisconsin Department of Public Instruction-protected.html")
)

report_galleries %>%
  cards(
    title = "SY21-22",
    footer = long_name,
    link = link,
    image = image_url,
    width = 2,
    layout = "inset-bottom",
    spacing = 3
  )
```


# SY20-21 Reports

<br>

<center> Passwords for Reports are [here](https://docs.google.com/spreadsheets/d/1eAUdWEzc0R7WzpztOvutRp2FYDtpks37LSFV8sq8ezg/edit?usp=sharing) which will only be viewable if you are a Teaching Lab employee. </center>

<br>

```{r echo = F, layout = "l-page"}
report_galleries <- tibble::tibble(
  location = c(
    "All Partners Report Unmatched",
    "Brownington",
    "Building 21",
    "Delaware Department of Education",
    "District 11",
    "East Baton Rouge",
    "Evangeline Parish",
    "Freire Charter",
    "Kankakee",
    "Lafayette Parish",
    "Legacy Early College",
    "Louisiana State",
    "Mississippi Department of Education",
    "NYC District 11 District-wide",
    "NYC District 11 - IS 355",
    "NYC District 11 - PS 21",
    "NYC District 11 - PS 87",
    "NYC District 11 - PS 89",
    "NYC District 11 - PS 96",
    "NYC District 11 - PS 103",
    "NYC District 11 - PS 189",
    "NYC District 11 - PS 498",
    "Pointe Coupee",
    "Tangipahoa Parish",
    "All Partners Report Matched"
  ),
  long_name = c(
    "All Partners SY21-22 Report Unmatched",
    "Personalized Report for: Brownington",
    "Personalized Report for: Building 21", "Personalized Report for: Delaware Department of Education",
    "Personalized Report for: District 11",
    "Personalized Report for: East Baton Rouge", "Personalized Report for: Evangeline Parish",
    "Personalized Report for: Freire Charter", "Personalized Report for: Kankakee",
    "Personalized Report for: Lafayette Parish",
    "Personalized Report for: Legacy Early College", "Personalized Report for: Louisiana State",
    "Personalized Report for: Mississippi Department of Education",
    "Personalized Report for: NYC District 11 District-wide", "Personalized Report for: NYC District 11 - IS 355",
    "Personalized Report for: NYC District 11 - PS 21", "Personalized Report for: NYC District 11 - PS 87",
    "Personalized Report for: NYC District 11 - PS 89", "Personalized Report for: NYC District 11 - PS 96",
    "Personalized Report for: NYC District 11 - PS 103", "Personalized Report for: NYC District 11 - PS 189",
    "Personalized Report for: NYC District 11 - PS 498", "Personalized Report for: Pointe Coupee",
    "Personalized Report for: Tangipahoa Parish",
    "All Partners SY21-22 Report Matched Sample"
  ),
  image_url = c(
    here::here("Images/Reports/Reports.png"),
    here::here("Images/Reports/ReportsMatched.png"),
    here::here("Images/Reports/BrowningtonReport.png"),
    here::here("Images/Reports/Building21Report.png"),
    here::here("Images/Reports/DelawareDoEReport.png"),
    here::here("Images/Reports/NYCD11D-wide.png"),
    here::here("Images/Reports/EastBatonReport.png"),
    here::here("Images/Reports/EvangelineReport.png"),
    here::here("Images/Reports/FreireReport.png"),
    here::here("Images/Reports/KankakeeReport.png"),
    here::here("Images/Reports/LafayetteReport.png"),
    here::here("Images/Reports/LegacyReport.png"),
    here::here("Images/Reports/LouisianaStateReport.png"),
    here::here("Images/Reports/MississippiDOEReport.png"),
    here::here("Images/Reports/NYCD11D-wide.png"),
    here::here("Images/Reports/NYCD11IS355.png"),
    here::here("Images/Reports/NYCD11PS21.png"),
    here::here("Images/Reports/NYCD11PS87.png"),
    here::here("Images/Reports/NYCD11PS89.png"),
    here::here("Images/Reports/NYCD11PS96.png"),
    here::here("Images/Reports/NYCD11PS103.png"),
    here::here("Images/Reports/NYCD11PS189.png"),
    here::here("Images/Reports/NYCD11PS498.png"),
    here::here("Images/Reports/PointeCoupeeReport.png"),
    here::here("Images/Reports/TangipahoaReport.png")
  ),
  link = c(
    "Encrypted/2021 Report_unmatched_All Partners-protected.html",
    "Encrypted/2021 Report_unmatched_Brownington Central School, VT-protected.html",
    "Encrypted/2021 Report_unmatched_Building 21-protected.html",
    "Encrypted/2021 Report_unmatched_Delaware Department of Education, DE-protected.html",
    "Encrypted/FinalReportDistrict11.html",
    "Encrypted/2021 Report_unmatched_East Baton Rouge Parish, LA-protected.html",
    "Encrypted/2021 Report_unmatched_Evangeline Parish, LA-protected.html",
    "Encrypted/DE-protected.html",
    "Encrypted/2021 Report_unmatched_Kankakee School District, IL-protected.html",
    "Encrypted/2021 Report_unmatched_Lafayette Parish, LA-protected.html",
    "Encrypted/2021 Report_unmatched_Legacy Early College, SC-protected.html",
    "Encrypted/2021 Report_unmatched_Louisiana State Content Leader Training, LA-protected.html",
    "Encrypted/2021 Report_unmatched_Mississippi Department of Education, MS-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - District-wide, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - IS 355, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 21, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 87, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 89, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 96, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 103, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 189, NY-protected.html",
    "Encrypted/2021 Report_unmatched_NYC District 11 - PS 498, NY-protected.html",
    "Encrypted/2021 Report_unmatched_Pointe Coupee Parish, LA-protected.html",
    "Encrypted/2021 Report_unmatched_Tangipahoa Parish, LA-protected.html",
    "Encrypted/2021 Report_matched_All Partners-protected.html"
  )
)

report_galleries %>%
  cards(
    title = "SY20-21",
    footer = long_name,
    link = link,
    image = image_url,
    width = 2,
    layout = "inset-bottom",
    spacing = 3
  )
```
