---
title: "Surveys Hub"
output: 
  distill::distill_article:
    css: css/theme.css
---

# 2021-2022 Survey Links


Please verify if the following links are available in Moodle and slide decks, and add if necessary.


* <strong>Attendance list</strong>: https://tinyurl.com/TL-attend


* <strong>Diagnostic Educator Survey. We are finding that we have higher completion rates when time is given in the first session to complete this</strong>. It's taking participants 5 minutes on average to complete, per Survey Monkey metrics.
  + Link: https://www.surveymonkey.com/r/diagnosticSY21-22


* <strong>Short knowledge assessments to be taken during the first and last session of PL</strong>. Knowledge assessments are taking around 5 min, per Survey Monkey metrics.
  + Please find the link to your course [here](https://docs.google.com/spreadsheets/d/1cELGsuEjXsb1e5oRdtdYof-Ul7jfdBXMOTYbIYd7nS4/edit?usp=sharing), under the tab “Knowledge Assessment Links”. We are drafting these in order of PL courses being implemented, so not all are ready yet. 


* <strong>End-of-Session Participant Feedback Survey to be taken after every PL session</strong>, except the final session (e.g., if there are 5 sessions, use this for Sessions #1-4). Please remind participants of which course they are taking. It's taking 2 min, per Survey Monkey metrics.
  + Link: https://www.surveymonkey.com/r/TLendofsession


* <strong>End-of-Course Participant Feedback Survey to be taken after the final PL session</strong> (e.g., if there are 5 sessions, use this for Session #5). Please remind participants of which course they are taking. It's taking 4 min, per Survey Monkey metrics.
  + Link: https://www.surveymonkey.com/r/TLendofcourse